const WHATSAPP_CONSTANTS = {
  GET_WHATSAPP_MESSAGE_REQUEST: 'GET_WHATSAPP_MESSAGE_REQUEST',
  GET_WHATSAPP_MESSAGE_SUCCESS: 'GET_WHATSAPP_MESSAGE_SUCCESS',
  GET_WHATSAPP_MESSAGE_FAIL: 'GET_WHATSAPP_MESSAGE_FAIL',
  
  UPDATE_WHATSAPP_MESSAGE_REQUEST: 'UPDATE_WHATSAPP_MESSAGE_REQUEST',
  UPDATE_WHATSAPP_MESSAGE_SUCCESS: 'UPDATE_WHATSAPP_MESSAGE_SUCCESS',
  UPDATE_WHATSAPP_MESSAGE_FAIL: 'UPDATE_WHATSAPP_MESSAGE_FAIL',
  UPDATE_WHATSAPP_MESSAGE_RESET: 'UPDATE_WHATSAPP_MESSAGE_RESET',

  GET_CONSTANT_REQUEST: 'GET_CONSTANT_REQUEST',
  GET_CONSTANT_SUCCESS: 'GET_CONSTANT_SUCCESS',
  GET_CONSTANT_FAIL: 'GET_CONSTANT_FAIL',

  UPDATE_CONSTANT_REQUEST: 'UPDATE_CONSTANT_REQUEST',
  UPDATE_CONSTANT_SUCCESS: 'UPDATE_CONSTANT_SUCCESS',
  UPDATE_CONSTANT_FAIL: 'UPDATE_CONSTANT_FAIL',
  UPDATE_CONSTANT_RESET: 'UPDATE_CONSTANT_RESET',
}

export default WHATSAPP_CONSTANTS