const WHATSAPP_CONSTANTS = {
  GET_WHATSAPP_MESSAGE_REQUEST: 'GET_WHATSAPP_MESSAGE_REQUEST',
  GET_WHATSAPP_MESSAGE_SUCCESS: 'GET_WHATSAPP_MESSAGE_SUCCESS',
  GET_WHATSAPP_MESSAGE_FAIL: 'GET_WHATSAPP_MESSAGE_FAIL',
  
  UPDATE_WHATSAPP_MESSAGE_REQUEST: 'UPDATE_WHATSAPP_MESSAGE_REQUEST',
  UPDATE_WHATSAPP_MESSAGE_SUCCESS: 'UPDATE_WHATSAPP_MESSAGE_SUCCESS',
  UPDATE_WHATSAPP_MESSAGE_FAIL: 'UPDATE_WHATSAPP_MESSAGE_FAIL',
  UPDATE_WHATSAPP_MESSAGE_RESET: 'UPDATE_WHATSAPP_MESSAGE_RESET',
}

export default WHATSAPP_CONSTANTS