export const EMPLOYEE_CONSTANTS = {
  NEW_EMPLOYEE_REQUEST: 'NEW_TAX_STATE_REQUEST',
  NEW_EMPLOYEE_SUCCESS: 'NEW_TAX_STATE_SUCCESS',
  NEW_EMPLOYEE_FAIL: 'NEW_TAX_STATE_FAIL',

  GET_EMPLOYEE_REQUEST: 'GET_ALL_STATES_REQUEST',
  GET_EMPLOYEE_SUCCESS: 'GET_ALL_STATES_SUCCESS',
  GET_EMPLOYEE_FAIL: 'GET_ALL_STATES_FAIL',

  UPDATE_EMPLOYEE_REQUEST: 'UPDATE_STATE_REQUEST',
  UPDATE_EMPLOYEE_SUCCESS: 'UPDATE_STATE_SUCCESS',
  UPDATE_EMPLOYEE_FAIL: 'UPDATE_STATE_FAIL',

  DELETE_EMPLOYEE_REQUEST: 'NEW_TAX_MODE_REQUEST',
  DELETE_EMPLOYEE_SUCCESS: 'NEW_TAX_MODE_SUCCESS',
  DELETE_EMPLOYEE_FAIL: 'NEW_TAX_MODE_FAIL',

  CLEAR_ERRORS: 'CLEAR_ERRORS',
}
