export const PUSH_NOTIFICATION_CONSTANTS = {
  SEND_PUSH_NOTIFICATION_REQUEST: 'SEND_PUSH_NOTIFICATION_REQUEST',
  SEND_PUSH_NOTIFICATION_SUCCESS: 'SEND_PUSH_NOTIFICATION_SUCCESS',
  SEND_PUSH_NOTIFICATION_FAIL: 'SEND_PUSH_NOTIFICATION_FAIL',
  SEND_PUSH_NOTIFICATION_RESET: 'SEND_PUSH_NOTIFICATION_RESET',

  GET_PUSH_NOTIFICATIONS_REQUEST: 'GET_PUSH_NOTIFICATIONS_REQUEST',
  GET_PUSH_NOTIFICATIONS_SUCCESS: 'GET_PUSH_NOTIFICATIONS_SUCCESS',
  GET_PUSH_NOTIFICATIONS_FAIL: 'GET_PUSH_NOTIFICATIONS_FAIL',
}
