export const TAX_CONSTANTS = {
  NEW_TAX_STATE_REQUEST: 'NEW_TAX_STATE_REQUEST',
  NEW_TAX_STATE_SUCCESS: 'NEW_TAX_STATE_SUCCESS',
  NEW_TAX_STATE_FAIL: 'NEW_TAX_STATE_FAIL',

  GET_ALL_STATES_REQUEST: "GET_ALL_STATES_REQUEST",
  GET_ALL_STATES_SUCCESS: "GET_ALL_STATES_SUCCESS",
  GET_ALL_STATES_FAIL: "GET_ALL_STATES_FAIL",

  UPDATE_STATE_REQUEST: "UPDATE_STATE_REQUEST",
  UPDATE_STATE_SUCCESS: "UPDATE_STATE_SUCCESS",
  UPDATE_STATE_FAIL: "UPDATE_STATE_FAIL",

  NEW_TAX_MODE_REQUEST: 'NEW_TAX_MODE_REQUEST',
  NEW_TAX_MODE_SUCCESS: 'NEW_TAX_MODE_SUCCESS',
  NEW_TAX_MODE_FAIL: 'NEW_TAX_MODE_FAIL',

  NEW_TAX_PRICE_REQUEST: 'NEW_TAX_PRICE_REQUEST',
  NEW_TAX_PRICE_SUCCESS: 'NEW_TAX_PRICE_SUCCESS',
  NEW_TAX_PRICE_FAIL: 'NEW_TAX_PRICE_FAIL',

  CLEAR_ERRORS: 'CLEAR_ERRORS',
}
