export const CREATE_TAX_MODE_REQUEST = 'CREATE_TAX_MODE_REQUEST'
export const CREATE_TAX_MODE_SUCCESS = 'CREATE_TAX_MODE_SUCCESS'
export const CREATE_TAX_MODE_FAIL = 'CREATE_TAX_MODE_FAIL'

export const GET_ALL_TAX_MODES_REQUEST = 'GET_ALL_TAX_MODES_REQUEST'
export const GET_ALL_TAX_MODES_SUCCESS = 'GET_ALL_TAX_MODES_SUCCESS'
export const GET_ALL_TAX_MODES_FAIL = 'GET_ALL_TAX_MODES_FAIL'

export const UPDATE_TAX_MODE_REQUEST = 'UPDATE_TAX_MODE_REQUEST'
export const UPDATE_TAX_MODE_SUCCESS = 'UPDATE_TAX_MODE_SUCCESS'
export const UPDATE_TAX_MODE_FAIL = 'UPDATE_TAX_MODE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
