export const WALLET_CONSTANTS = {
  GET_WITHDRAWALS_REQUEST: 'GET_WITHDRAWALS_REQUEST',
  GET_WITHDRAWALS_SUCCESS: 'GET_WITHDRAWALS_SUCCESS',
  GET_WITHDRAWALS_FAIL: 'GET_WITHDRAWALS_FAIL',

  COMPLETE_WITHDRAWAL_REQUEST: 'COMPLETE_WITHDRAWAL_REQUEST',
  COMPLETE_WITHDRAWAL_SUCCESS: 'COMPLETE_WITHDRAWAL_SUCCESS',
  COMPLETE_WITHDRAWAL_FAIL: 'COMPLETE_WITHDRAWAL_FAIL',
  COMPLETE_WITHDRAWAL_RESET: 'COMPLETE_WITHDRAWAL_RESET',

  REJECT_WITHDRAWAL_REQUEST: 'REJECT_WITHDRAWAL_REQUEST',
  REJECT_WITHDRAWAL_SUCCESS: 'REJECT_WITHDRAWAL_SUCCESS',
  REJECT_WITHDRAWAL_FAIL: 'REJECT_WITHDRAWAL_FAIL',
  REJECT_WITHDRAWAL_RESET: 'REJECT_WITHDRAWAL_RESET',

  REFUND_TO_WALLET_REQUEST: 'REFUND_TO_WALLET_REQUEST',
  REFUND_TO_WALLET_SUCCESS: 'REFUND_TO_WALLET_SUCCESS',
  REFUND_TO_WALLET_FAIL: 'REFUND_TO_WALLET_FAIL',
  REFUND_TO_WALLET_RESET: 'REFUND_TO_WALLET_RESET',
}
